### ISSUE TITLE
Recurruring tasks not displayed in obsidian pane

### ISSUE THREAD

**Issue by sessionsdev** [YukiGasai/obsidian-google-tasks#10]
There is an issue with recurring tasks.

To reproduce:
Create a recurring task via google calendar with any recurrence rule.  

Result:
The plugin pane will display only the first instance of the recurring task and none of the subsequent tasks.

Expected Result:
All instances of the task display correctly on the days they are due.

**Comment by sessionsdev** [comment]
Hey @YukiGasai - me again.  lol

Seems like the recurrences of a task instance aren't treated as tasks themselves, so are not fetched with the GET.

Not sure what the level of effort is here.  If it's a google api limitation I'll just close the issue.

**Comment by YukiGasai** [comment]
Sadly, the API is missing the option `singleEvents` that the [Google Calendar Api](https://developers.google.com/calendar/api/v3/reference/events/list) has, so I don't really see how to make it possible. Sorry.
