### ISSUE TITLE
Interacting with Tasks via Markdown

### ISSUE THREAD

**Issue by pat-richter** [YukiGasai/obsidian-google-tasks#12]
Hey,

thanks so much for your effort.

**A: I would like to see some feedback of an created task within Obsidian.**

When I create a task, it should be possible to return a line for this single task, like

`- [ ] 2022-11-30  This is my task title  %%kOk1ZXBwYUxfabbbRk9xcA%%`

Why? A note **wedding event** should have a list with all the associated tasks. I want to build my list, so I can also create subtasks and see basic dependencies.

I can't add them to different lists in Google Tasks and "insert" only this list, since I use another service called Reclaim.ai to let them schedule my tasks around fixed appointments. (You may use my link to check them out, if you like [reclaim](bit.ly/reclaimai) )

**B: I would like to see completed tasks as marked**

When I open the event note again, I would like to see which tasks are already done and which have to be done within Obsidian. If `- [ ] 2022-11-30  This is my task title  %%kOk1ZXBwYUxfabbbRk9xcA%%` is marked as completed in Tasks, it should also be marked as complete in my note (probably updated on open).

**Comment by YukiGasai** [comment]
Hello @pat-richter,

I added your idea to sync the task with the Google API on open. 
To create and insert, I added a new command `Create Google Tasks and insert it`.
You should also be able to change the status of the task by clicking the checkbox.

If you have time, please test it yourself.

**Comment by pat-richter** [comment]
Works as expected! This is really awesome, thank you so much.

One issue *could* be that changes within Google Tasks like "title" are not reflected within Obsidian. It's not an important issue for me, but might be for others.

You might close the issue, I'm very happy!

**Comment by YukiGasai** [comment]
Need to reopen this as it causes file corruptions in attachments #17 
Automatic syncing was the problem.

**Comment by pat-richter** [comment]
I've checked #17 and it seems to work now. #12 also is not disabled, so you might close the issue again?

**Comment by YukiGasai** [comment]
Automatically syncing the task status in the file was deactivated and should now work again. I added a check to only test markdown files.
