### ISSUE TITLE
¿ Synch. task parameters between "obsidian" & "google task" ?

### ISSUE THREAD

**Issue by anatoliibakhtin** [YukiGasai/obsidian-google-tasks#14]
Hi I am using the [tasks](https://obsidian-tasks-group.github.io/obsidian-tasks/) plugin It allows me to collect all tasks from all notes, excalidraw drawings into one place where I arrange them by priority, date. It doesn't work with notifications and the [notification](https://github.com/uphy/obsidian-reminder#:~:text=System%20notification%20in%20mobile%20device%20is%20not%20available%20because%20Obsidian%20doesn%27t%20provide%20the%20feature.) plugin can't notify the user outside the mobile app. (maybe the developers themselves will solve this issue later, since they have a task plugin in the road [map](https://trello.com/c/RFOpqtra/93-tasks)) 

As a temporary or permanent solution I found you, I want to ask if your plugin provides synchronization between "- [ ] obsidian tasks", looking for them in all the files checking with "tasks from google tasks" , so that its completion status (cool if and date) will be displayed everywhere the same? Or does your plugin like iframe display, allowing only interacting with tasks from google tasks list + interacting with obsidian only importing, without exporting back from google tasks to obsidian?

Thanks for your attention !

**Comment by YukiGasai** [comment]
I tested this with the task plugin, and it should still work.

**Comment by anatoliibakhtin** [comment]
Cool ! I assume excalidraw works too, because both of them leave a hidden identifier not on the first place from the end of the line . THANK YOU ! I join in !
