### ISSUE TITLE
Installs on Android but will not enable

### ISSUE THREAD

**Issue by ElCid87** [YukiGasai/obsidian-google-tasks#15]
I installed the plugin, but get an error message "Failed to load plugin obsidian-google-tasks" when I try to enable.

**Comment by YukiGasai** [comment]
Hi, I was able to reproduce this and will work on a solution.

**Comment by YukiGasai** [comment]
@ElCid87,
there was a deprecated package for fetching that didn't work on mobile.
Please test the latest version on your device.

**Comment by ElCid87** [comment]
I will test it today and revert with the results

**Comment by ElCid87** [comment]
@YukiGasai SUCCESS!

I downloaded from community, quit Obsidian, downloaded the latest release from Git, moved files to the obsidian-google-tasks folder, restarted obsidian and was successful with the enable.

Now to finish the rest of the setup
