### ISSUE TITLE
Version 1.4.7 seems to corrupt attachments on Obsidian 1.1.8

### ISSUE THREAD

**Issue by carlosrusso** [YukiGasai/obsidian-google-tasks#17]
For some reason, whenever the I use this plugin with Obsidian 1.1.8, the attachments become corrupted after I view them for the first time. 
I am under the impression this worked fine on obsidian 1.0.3.
  
To reproduce this, simply alternate viewing between two images while the Google Tasks plugin 1.4.7 is active in Obsidian 1.1.8. 

Fortunately I have git, and I can use that to recover the corrupted files.

**Comment by YukiGasai** [comment]
@carlosrusso thank you for bringing this to my attention. I was able to reproduce this once. It only corrupted a single attachment. Have you found a reliable method to cause this?

PS: THANK YOU GIT

**Comment by YukiGasai** [comment]
From my testing, the problem is resolved. If you have the time, it would be cool if you could verify this.

**Comment by carlosrusso** [comment]
To reproduce the issue, all I did was alternate between various attachments several times. It seemed that the file was corrupted after the first visit, when switching to the next attachment (image, pdf).
I updated to the latest version and the problem is apparently fixed, thank you very much!

**Comment by pat-richter** [comment]
I've tested the issue and could also reproduce the issue with my latest version 1.4.7. I've updated to 1.5 and could not reproduce the issue. Thanks for the fast solution and thanks for finding the problem @carlosrusso

**Comment by YukiGasai** [comment]
The problem was reading and writing binary data like text. I added a check to #12 to make sure only markdown files are checked.
