### ISSUE TITLE
gogle task missing settings or not logged in

### ISSUE THREAD

**Issue by mecaloza** [YukiGasai/obsidian-google-tasks#18]
Hi i already did all the step but dosent login scuccesfully.

![image](https://user-images.githubusercontent.com/35116182/209366081-4e8ecee9-b4b2-446a-8113-435de2745e89.png)

![image](https://user-images.githubusercontent.com/35116182/209366015-082f3a3a-a751-4aa5-8ba8-ef2030f6c489.png)

**Comment by YukiGasai** [comment]
Hi @mecaloza,
please make sure to update to the latest version.

Did you get the Google authentication screen?

If you have a VPN enabled, please disconnect from it.
If not, please take a look at [this](https://kinsta.com/knowledgebase/err_connection_reset/)

**Comment by mecaloza** [comment]
Thankss
