### ISSUE TITLE
Add option to filter inserted tasks

### ISSUE THREAD

**Issue by pontifex9355** [YukiGasai/obsidian-google-tasks#19]
Hi!
It would be really cool if we could filter what tasks will be inserted through `Insert Google Tasks` command.
For example, I'd like to insert only the tasks for today, or to insert only tasks from a certain list. Currently all tasks are inserted and, when you have a lot of tasks, it can really bloat the note.

ps. thanks for an amazing plugin!

**Comment by YukiGasai** [comment]
Hi, this feature is added in the latest version.
