### ISSUE TITLE
Google api token

### ISSUE THREAD

**Issue by meherjammula** [YukiGasai/obsidian-google-tasks#21]
I am not sure what to put in the google API token. I have client id and client secret. But neither the instructions are mentioned on Google API token. how to get that?

<img width="424" alt="SCR-20230313-lbop-2" src="https://user-images.githubusercontent.com/30104025/224627763-6b6a1c79-f286-4b3d-9c8e-dbab382c3bad.png">

**Comment by YukiGasai** [comment]
Hi, with the next release, the need for an API is removed.
