### ISSUE TITLE
Update markdown on task change

### ISSUE THREAD

**Issue by nilsherzig** [YukiGasai/obsidian-google-tasks#23]
hi, thanks for your work :) 

Is it possible to update the inserted tasks automatically, or do I have to re-run the "insert uncompleted google tasks" command? 

I know there is a sidebar, but i would really like them to be in my default markdown tasks file and update themselves :)

**Comment by YukiGasai** [comment]
Hi, the tasks inserted by the `Insert Google Task` command should update if the file is reopened.
The task doesn't update in an interval to prevent unintended overwrites.

**Comment by nilsdev** [comment]
My apologies for not being clear earlier. While modifications (completed or incomplete) are reflected in the markdown, any new tasks created within the Google Tasks app do not get automatically added to the markdown file.
