### ISSUE TITLE
Login yields redirect_uri_mismatch error 

### ISSUE THREAD

**Issue by Near32** [YukiGasai/obsidian-google-tasks#29]
Following the installation steps (note: configuring as a Web Application instead of Webclient, no longer visible in the dropdown menu), I am trying to login from the settings page of the plugin, and I am facing google's login page in my web browser that offers this explanation : 

> Access blocked: This app’s request is invalid
> You can’t sign in because this app sent an invalid request. You can try again later or contact the developer about this issue. [Learn more about this error](https://developers.google.com/identity/protocols/oauth2/web-server#authorization-errors-redirect-uri-mismatch)
> If you are a developer of this app, see error details.
>
> Error 400: redirect_uri_mismatch

With the erro details link yielding the following information in a popup : 

> Error 400: redirect_uri_mismatch
> 
> You can't sign in to this app because it doesn't comply with Google's OAuth 2.0 policy.
> 
> If you're the app developer, register the redirect URI in the Google Cloud Console.
> Request details: redirect_uri=http://127.0.0.1:42813/callback

> [Related developer documentation](https://developers.google.com/identity/protocols/oauth2/web-server#authorization-errors-redirect-uri-mismatch)

I am not sure what am I missing as the uri is registered : 
![screenshot-google-cloud-uri](https://github.com/YukiGasai/obsidian-google-tasks/assets/6569683/6a37d3f1-b028-4841-8bc6-3a26079e09b0)

Please let me know what I can do to remedy this issue?

Kind regards

**Comment by YukiGasai** [comment]
make sure to use `http` not `https`

**Comment by YukiGasai** [comment]
Please try and use `http` instead of `https`

**Comment by Near32** [comment]
It solved the issue, thank you very much!!
