### ISSUE TITLE
Description of a task is a bit small, making it difficult to read.

### ISSUE THREAD

**Issue by jonathanraxa** [YukiGasai/obsidian-google-tasks#30]
![Screenshot 2023-10-30 at 10 46 13 AM](https://github.com/YukiGasai/obsidian-google-tasks/assets/5641096/359e4cc2-27d4-4de0-b4c1-74897621264c)

**Comment by jonathanraxa** [comment]
@YukiGasai - thanks for building this out!

I was wondering if you'd like some help with this? I use Obsidian and Google Tasks on a daily basis and I'm excited that you have a plugin for these applications. I'd love to help contribute!

**Comment by YukiGasai** [comment]
Thank you for this update.
