### ISSUE TITLE
Successful login, but plugin isn't showing

### ISSUE THREAD

**Issue by noamsiegel** [YukiGasai/obsidian-google-tasks#4]
Amazing idea, but I can't seem to get it to work.

The checklist icon is on the left sidebar, but no action is triggered when clicked. I completed the step-by-step process on the documentation, but for reference, I am not experienced with  API frameworks.

Let me know if there are any details you want!

**Comment by YukiGasai** [comment]
Thank you ^^

No action seems a little odd.

### Reinstall
1. Press Logout in the settings page
2. Reinstall the plugin without adding credentials

When pressing the icon, you should get this notification
![grafik](https://user-images.githubusercontent.com/38146192/165506150-21793a0c-894a-4d62-bfdc-bb43ca4001f7.png)

If not, please check your dev console.


If there are no errors so far, try logging in.
### Login 
1. Enter your credentials again 
2. Login to your Google account

Are you logged into a Google account, did the browser open with the auth screen?
Did the browser redirect you to a page saying `Authentication successful! Please return to obsidian.`
When you are pressing the Icon are there any error in the dev console?

If there are errors, please send them and we can figure out what's going on.

**Comment by noamsiegel** [comment]
Good catch with the dev console, there are errors:

[image: image.png]

It seems that the API token I entered isn't right, but I can't seem to find
it on the google developer dashboard.

To answer your questions:

   1. Are you logged into a Google account, and did the browser open with
   the auth screen? *YES*
   2. Did the browser redirect you to a page saying "Authentication
   successful! Please return to obsidian." *YES*
   3. When you are pressing the Icon are there any errors in the dev
   console?* YES, all are embedded above*

My Client ID and secret are definitely correct though. Token, not so sure.

I am more than willing to do a quick video on how I *eventually* set it up
so that you can forward it to others with similar issues.

Thanks for the help,
Noam

**Comment by YukiGasai** [comment]
The image upload didn't work, but it could be the API token have a look at this issue #5 

The Token has to fit this regex `AIza[0-9A-Za-z-_]{35}`

You can find it inside the [API console](https://console.cloud.google.com/apis/credentials)
![grafik](https://user-images.githubusercontent.com/38146192/165607678-dc12b753-12c3-4577-9be7-3932417cccbb.png)

**Comment by YukiGasai** [comment]
Nice and thank you. If you want to make a installation guide just open another issue or create a pull request.
