### ISSUE TITLE
Successfull login but no tasks shown...

### ISSUE THREAD

**Issue by ccjcan** [YukiGasai/obsidian-google-tasks#5]
Open the side bar, commands are available via Cmd+P but no tasks shown.
Does the plugin expects a specific name for Google Tasks List?

**Comment by YukiGasai** [comment]
The plugin should list all tasks from every list when using the `List Google Tasks` command
Are you logged into the right google account?
Are there any errors in the dev console?

**Comment by YukiGasai** [comment]
There seems to be a problem with the API token, the part after the `?key=` in the URL should contain the API Token from Google. Please make sure there are no spaces in settings input. 

I'm trying to reproduce your error using my working token, but it could take some time.

**Comment by ccjcan** [comment]
I'm extracting my token from the .json downloaded from Google
(client_secret ... dot json..)
it looks like this : https://oauth2.googleapis.com/token
Is this the wrong parameter?
the .json file includes: client_id, project_id, token_uri (the one I'm
using for the token parameter in your
plugin), auth_provider_x509_cert_url, client_secret, redirect_uris

Let me know and thanks.

**Comment by YukiGasai** [comment]
The token is a random combination of numbers and letters, you can find it inside the API console
![grafik](https://user-images.githubusercontent.com/38146192/165595407-a119599e-c898-44a1-9f59-72e9dcfb7a9f.png)
just press "Schlüssel Anzeigen" Press Key on the right

**Comment by ccjcan** [comment]
Problem solved. I had to do go Credentials and then API Keys... this gave me the key (token i guess) I entered in your plugin and it worked.
