### ISSUE TITLE
Incompatible device?

### ISSUE THREAD

**Issue by bitcloudTheFirst** [YukiGasai/obsidian-google-tasks#6]
Hi, on both my iPad and Android devices I get an incompatible device message. 

Is this in error?

**Comment by YukiGasai** [comment]
Sadly not, my method to authenticate with google currently only supports desktop devices.

**Comment by YukiGasai** [comment]
I made a new Version (1.3.0) with a work around that is functioning for android, not tested on IOS.

### Requirements 
- Installation on PC


### Install
- Uninstall plugin
- Install the plugin via the browse page
- Fill in all fields in settings
- follow the new [ReadMe](https://github.com/YukiGasai/obsidian-google-tasks#google-task-view) to skip the login
