### ISSUE TITLE
obsidian-google-keep

### ISSUE THREAD

**Issue by backmind** [YukiGasai/obsidian-google-tasks#8]
Hey, Yuki, great work here!

What do you think about adding **Google Keep** support? Would it be hard? I was messing with [Keep's API](https://developers.google.com/keep/api/reference/rest) and seems almost the same. I could try, but no idea of typescript on my side.

**Comment by YukiGasai** [comment]
Hi, thank you

I was thinking about that as well, but decided that google calendar is more important for now. So I am currently working on that. It is something interesting for the future, tho.

As a workaround, I would suggest taking a look at this plugin. 
[ObsidianCustomFrames](https://github.com/Ellpeck/ObsidianCustomFrames)
